id: cesium_coating_application_v0
kind: process
name: Cesium coating application on cathode v0
layer_tags:
- layer_5
- layer_6
inputs:
- item_id: cathode_coated
  qty: 1.0
  unit: unit
- item_id: cesium_ampule
  qty: 1.0
  unit: unit
outputs:
- item_id: cathode_low_work_function_v0
  qty: 1.0
  unit: unit
resource_requirements:
- resource_type: coating_station
  qty: 1.0
  unit: hr
- resource_type: labor_bot_general
  qty: 0.5
  unit: hr
energy_model:
  type: kWh_per_unit
  value: 0.5
notes: "Cesium coating application to oxide-coated cathode to reduce work function."
time_model:
  type: fixed_time
  hr_per_batch: 1.0
